- name: Onboard linux asset to ELK
  hosts: all
  become: yes
  # vars_files:
  # - ELK_secret.yml
  vars:
    enrollment_token: "TOKEN"
    ip_addr: "IP_SERVEUR" # ADRESSE IP DU SERVEUR

  tasks:
    - name: Download Elastic Agent
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.0-linux-x86_64.tar.gz
        dest: /tmp/elastic-agent-9.0.0-linux-x86_64.tar.gz
        mode: '0644'

    - name: Extract Elastic Agent archive
      ansible.builtin.unarchive:
        src: /tmp/elastic-agent-9.0.0-linux-x86_64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Elastic Agent
      ansible.builtin.command:
        cmd: ./elastic-agent-9.0.0-linux-x86_64/elastic-agent install --url=http://{{ ip_addr }}:8220 --enrollment-token={{ enrollment_token }} --insecure --non-interactive --force
        chdir: /tmp
      register: install_output
      ignore_errors: no  # optionnel, selon le niveau de tolérance que tu veux

    - name: Afficher la sortie de l'install
      ansible.builtin.debug:
        msg: "{{ install_output.stdout }}"

    - name: Clean up Elastic Agent tarball
      ansible.builtin.file:
        path: /tmp/elastic-agent-9.0.0-linux-x86_64.tar.gz
        state: absent

    - name: Clean up extracted Elastic Agent directory
      ansible.builtin.file:
        path: /tmp/elastic-agent-9.0.0-linux-x86_64
        state: absent

    - name: Waiting for launching
      ansible.builtin.pause:
        seconds: 10

    - name: Install Elastic Agent
      ansible.builtin.command:
        cmd: /usr/bin/elastic-agent status
      register: install_status
      ignore_errors: yes 

    - name: Install terminée
      ansible.builtin.debug:
        msg: "{{ install_status.stdout }}"