---
- name: Setup Docker-ELK stack with custom configs
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - elk_secret.yml

  tasks:
    - name: Détection d'erreurs système critiques
      shell: >
        curl -k -u elastic:changeme
        -X POST "http://{{ kibana_host }}:5601/api/alerting/rule"
        -H "kbn-xsrf: true"
        -H "Content-Type: application/json"
        --data '{"params":{"index":["logs-*"],"timeField":"@timestamp","esQuery":"{\"query\":{\"bool\":{\"should\":[{\"query_string\":{\"query\":\"message:(\\\"kernel panic\\\" OR \\\"oom-killer\\\" OR \\\"segfault\\\" OR \\\"disk failure\\\")\"}}]}}}","size":100,"threshold":[0],"thresholdComparator":">","timeWindowSize":1,"timeWindowUnit":"m"},"consumer":"alerts","rule_type_id":".es-query","schedule":{"interval":"1m"},"name":"Erreur système critique détectée","tags":["système","erreur","critique"],"actions":[]}'

    - name: Détection de redémarrages multiples
      shell: >
        curl -k -u elastic:changeme
        -X POST "http://{{ kibana_host }}:5601/api/alerting/rule"
        -H "kbn-xsrf: true"
        -H "Content-Type: application/json"
        --data '{"params":{"index":["logs-*"],"timeField":"@timestamp","esQuery":"{\"query\":{\"match_phrase\":{\"message\":\"reboot\"}}}","size":100,"threshold":[2],"thresholdComparator":">","timeWindowSize":24,"timeWindowUnit":"h"},"consumer":"alerts","rule_type_id":".es-query","schedule":{"interval":"5m"},"name":"Détection de redémarrages multiples","tags":["système","reboot"],"actions":[]}'

    - name: Surveillance de la charge CPU
      shell: >
        curl -k -u elastic:changeme
        -X POST "http://{{ kibana_host }}:5601/api/alerting/rule"
        -H "kbn-xsrf: true"
        -H "Content-Type: application/json"
        --data '{"params":{"index":["metrics-*"],"timeField":"@timestamp","esQuery":"{\"query\":{\"range\":{\"system.cpu.total.norm.pct\":{\"gte\":0.85}}}}","size":1,"threshold":[0],"thresholdComparator":">","timeWindowSize":5,"timeWindowUnit":"m"},"consumer":"alerts","rule_type_id":".es-query","schedule":{"interval":"1m"},"name":"Surveillance de la charge CPU","tags":["performance","cpu"],"actions":[]}'

    - name: Surveillance de l'utilisation de la mémoire RAM
      shell: >
        curl -k -u elastic:changeme
        -X POST "http://{{ kibana_host }}:5601/api/alerting/rule"
        -H "kbn-xsrf: true"
        -H "Content-Type: application/json"
        --data '{"params":{"index":["metrics-*"],"timeField":"@timestamp","esQuery":"{\"query\":{\"range\":{\"system.memory.used.pct\":{\"gte\":0.9}}}}","size":1,"threshold":[0],"thresholdComparator":">","timeWindowSize":5,"timeWindowUnit":"m"},"consumer":"alerts","rule_type_id":".es-query","schedule":{"interval":"1m"},"name":"Surveillance de la mémoire RAM","tags":["performance","mémoire"],"actions":[]}'

    - name: Détection d'une machine arrêtée
      shell: |
        curl -k -u elastic:changeme \
          -X POST "http://{{ kibana_host }}:5601/api/alerting/rule" \
          -H "kbn-xsrf: true" \
          -H "Content-Type: application/json" \
          --data "{\"params\":{\"index\":[\"logs-*\"],\"timeField\":\"@timestamp\",\"esQuery\":\"{\\\"query\\\":{\\\"match_all\\\":{}}}\",\"size\":1,\"threshold\":[0],\"thresholdComparator\":\"<\",\"timeWindowSize\":1,\"timeWindowUnit\":\"m\"},\"consumer\":\"alerts\",\"rule_type_id\":\".es-query\",\"schedule\":{\"interval\":\"1m\"},\"name\":\"Détection d'une machine arrêtée\",\"tags\":[\"système\",\"inactivité\"],\"actions\":[]}"

    - name: Surveillance de l'espace disque
      shell: |
        curl -k -u elastic:changeme \
          -X POST "http://{{ kibana_host }}:5601/api/alerting/rule" \
          -H "kbn-xsrf: true" \
          -H "Content-Type: application/json" \
          --data "{\"params\":{\"index\":[\"metrics-*\"],\"timeField\":\"@timestamp\",\"esQuery\":\"{\\\"query\\\":{\\\"range\\\":{\\\"system.filesystem.available.pct\\\":{\\\"lte\\\":0.1}}}}\",\"size\":1,\"threshold\":[0],\"thresholdComparator\":\"<\",\"timeWindowSize\":5,\"timeWindowUnit\":\"m\"},\"consumer\":\"alerts\",\"rule_type_id\":\".es-query\",\"schedule\":{\"interval\":\"1m\"},\"name\":\"Surveillance de l'espace disque\",\"tags\":[\"stockage\",\"disque\"],\"actions\":[]}"

    - name: Surveillance de l'utilisation du swap
      shell: |
        curl -k -u elastic:changeme \
          -X POST "http://{{ kibana_host }}:5601/api/alerting/rule" \
          -H "kbn-xsrf: true" \
          -H "Content-Type: application/json" \
          --data "{\"params\":{\"index\":[\"metrics-*\"],\"timeField\":\"@timestamp\",\"esQuery\":\"{\\\"query\\\":{\\\"range\\\":{\\\"system.memory.swap.used.pct\\\":{\\\"gte\\\":0.2}}}}\",\"size\":1,\"threshold\":[0],\"thresholdComparator\":\">\",\"timeWindowSize\":5,\"timeWindowUnit\":\"m\"},\"consumer\":\"alerts\",\"rule_type_id\":\".es-query\",\"schedule\":{\"interval\":\"1m\"},\"name\":\"Surveillance de l'utilisation du swap\",\"tags\":[\"mémoire\",\"swap\"],\"actions\":[]}"

