---
- name: Create a user with sudo privileges
  hosts: all
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: username  # Replace with desired username
        password: "{{ 'your_password' | password_hash('sha512') }}"  # Replace 'your_password' with the actual password
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: username  # Replace with the same username
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^username'
        line: 'username ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'